name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#     - run: sudo chown -R 
#     - run: cd /root/urganch-ttb/server
    - run: npm install
    - run: npm run build --if-present
    - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash && export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && nvm install 16 && npm install --location=global yarn && npm install -g pm2 && pm2 restart 0 && pm2 logs 0
#     - run: npm test
    # - run: rm -rf /var/www/build && mv ./build /var/www/
